apiVersion: v2
appVersion: "1.16.0"
description: |
  This charts deploy a sample ToDo application to help you exercise with Kubernetes
name: todo
version: 0.1.1
maintainers:
- name: mmingorance-dh
- name: mifonpe
engine: gotpl
icon: https://github.com/kubernetes/kubernetes/raw/master/logo/logo.png
keywords:
- todo
- demo
home: https://github.com/gitops-helm-summit
