apiVersion: v2
name: argo-rollout-demo
description: |
  This chart deploys a sample Argo Rollout application
type: application
version: 0.2.6
appVersion: blue
maintainers:
- name: mmingorance-dh
  url: https://github.com/mmingorance-dh
- name: mifonpe
  url: https://github.com/mifonpe
icon: https://github.com/kubernetes/kubernetes/raw/master/logo/logo.png
keywords:
- argocd
- argocd-rollouts
- rollouts
- argo-rollout-demo
home: https://github.com/mifonpe/argocd-gitops-demo
